- type: entity
  id: VehicleEquipmentBase
  parent: BaseItem
  abstract: true
  components:
    - type: Appearance
    - type: Damageable
      damageModifierSet: VehicleLightArmor
    - type: Injurable
      damageContainer: StructuralInorganic
    - type: Item
      size: Normal
      shape:
      - 0, 0, 1, 1
    - type: Destructible
      thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 100
        behaviors:
        - !type:PlaySoundBehavior
          sound:
            collection: MetalBreak
        - !type:DoActsBehavior
          acts: ["Breakage"]

- type: entity
  id: VehicleEquipmentBaseBig
  parent: VehicleEquipmentBase
  abstract: true
  components:
    - type: Item
      size: Large
      shape:
      - 0, 0, 2, 2
    - type: MultiHandedItem
    - type: HeldSpeedModifier
      sprintModifier: 0.7
      walkModifier: 0.7