- type: playTimeTracker # Used as a tracker for all borgs and midround borging.
  id: JobSecBorg

- type: playTimeTracker
  id: JobCorpsman

- type: playTimeTracker
  id: JobCC-CADOfficial

- type: playTimeTracker
  id: JobCC-CSDOfficial

- type: playTimeTracker
  id: JobCC-CIDOfficial

# upstream removed boxer and zookeeper, readding it here
- type: playTimeTracker
  id: JobBoxer

- type: playTimeTracker
  id: JobZookeeper

# NSHC

- type: playTimeTracker
  id: JobHighCommandOfficial

- type: playTimeTracker
  id: JobHC-COAOfficial

- type: playTimeTracker
  id: JobHC-GWSOfficial

- type: playTimeTracker
  id: JobHC-DCIOfficial