- type: jobRequirementOverride
  id: FHJobRequirements
  jobs:
    NanoTrasenRepresentative:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Command
            time: 21600  # 6 hours
          - !type:OverallPlaytimeRequirement
            time: 72000 # 20 hours overall playtime
          - !type:RoleTimeRequirement
            role: JobCaptain
            time: 7200 # 2 hours
          - !type:RoleTimeRequirement
            role: JobHeadOfPersonnel
            time: 7200 # 2 hours
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobNanoTrasenRepresentative
            time: 14400 # 4 hours
    BlueShield:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Security
            time: 21600  # 6 hours
          - !type:DepartmentTimeRequirement
            department: Command
            time: 7200  # 2 hours
          - !type:OverallPlaytimeRequirement
            time: 72000 # 20 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobBlueShield
            time: 14400 # 4 hours
    Magistrate:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Security
            time: 21600  # 6 hours
          - !type:RoleTimeRequirement
            role: JobHeadOfPersonnel
            time: 7200 # 2 hours
          - !type:OverallPlaytimeRequirement
            time: 72000 # 20 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobMagistrate
            time: 14400 # 4 hours
    IAA:
      - !type:DepartmentTimeRequirement
        department: Security
        time: 14400  # 4 hours
      - !type:OverallPlaytimeRequirement
          time: 14400  # 4 hours
    Captain:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Command
            time: 21600  # 6 hours
          - !type:DepartmentTimeRequirement
            department: Security
            time: 7200  # 2 hours
          - !type:DepartmentTimeRequirement
            department: Engineering
            time: 7200  # 2 hours
          - !type:DepartmentTimeRequirement
            department: Medical
            time: 7200  # 2 hours
          - !type:DepartmentTimeRequirement
            department: Science
            time: 7200  # 2 hours
          - !type:DepartmentTimeRequirement
            department: Cargo
            time: 7200  # 2 hours
          - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobCaptain
            time: 14400 # 4 hours
    HeadOfPersonnel:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Civilian
            time: 14400  # 4 hours
          - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobHeadOfPersonnel
            time: 14400 # 4 hours
    HeadOfSecurity:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Security
            time: 21600  # 6 hours
          - !type:RoleTimeRequirement
            role: JobWarden
            time: 7200  # 2 hours
          - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobHeadOfSecurity
            time: 14400 # 4 hours
    ChiefEngineer:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Engineering
            time: 21600  # 6 hours
          - !type:RoleTimeRequirement
            role: JobAtmosphericTechnician
            time: 7200  # 2 hours
          - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobChiefEngineer
            time: 14400 # 4 hours
    ResearchDirector:
      - !type:DepartmentTimeRequirement
        department: Science
        time: 14400  # 4 hours
      - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
    ChiefMedicalOfficer:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Medical
            time: 21600  # 6 hours
          - !type:RoleTimeRequirement
            role: JobChemist
            time: 7200  # 2 hours
          - !type:RoleTimeRequirement
            role: JobSurgeon
            time: 3600  # 1 hour
          - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobChiefMedicalOfficer
            time: 14400 # 4 hours
    Quartermaster:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Cargo
            time: 21600  # 6 hours
          - !type:RoleTimeRequirement
            role: JobSalvageSpecialist
            time: 3600  # 1 hour
          - !type:RoleTimeRequirement
            role: JobCargoTechnician
            time: 3600  # 1 hour
          - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobQuartermaster
            time: 14400 # 4 hours
    MedicalDoctor:
      - !type:OverallPlaytimeRequirement
        time: 0
    Chemist:
      - !type:DepartmentTimeRequirement
        department: Medical
        time: 7200  # 2 hours
      - !type:OverallPlaytimeRequirement
        time: 0
    Paramedic:
      - !type:OverallPlaytimeRequirement
        time: 0
    Surgeon:
      - !type:OverallPlaytimeRequirement
        time: 0
    StationEngineer:
      - !type:OverallPlaytimeRequirement
        time: 0
    AtmosphericTechnician:
      - !type:OverallPlaytimeRequirement
        time: 0
    Warden:
      - !type:DepartmentTimeRequirement
        department: Security
        time: 14400 # 4 hours
      - !type:OverallPlaytimeRequirement
        time: 21600  # 6 hours
    SecurityCadet:
      - !type:OverallPlaytimeRequirement
        time: 14400  # 4 hours
    SecurityOfficer:
      - !type:OverallPlaytimeRequirement
        time: 14400  # 4 hours
    Detective:
      - !type:OverallPlaytimeRequirement
        time: 14400  # 4 hours
    Brigmedic:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Medical
            time: 7200  # 2 hours
          - !type:DepartmentTimeRequirement
            department: Security
            time: 7200  # 2 hours
          - !type:OverallPlaytimeRequirement
            time: 14400  # 4 hours
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobBrigmedic
            time: 14400 # 4 hours
    SecBorg:
      - !type:CompositeRequirement
        requirements:
          - !type:OverallPlaytimeRequirement
            time: 14400  # 4 hours
          - !type:DepartmentTimeRequirement
            department: Security
            time: 7200  # 2 hours
          - !type:RoleTimeRequirement
            role: JobBorg
            time: 7200  # 2 hours as Borg
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobSecBorg
            time: 14400 # 4 hours
    Corpsman:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Medical
            time: 7200  # 2 hours
          - !type:DepartmentTimeRequirement
            department: Security
            time: 7200  # 2 hours
          - !type:OverallPlaytimeRequirement
            time: 14400  # 4 hours
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobCorpsman
            time: 14400 # 4 hours
    StationAi:
      - !type:CompositeRequirement
        requirements:
          - !type:DepartmentTimeRequirement
            department: Command
            time: 7200  # 2 hours
          - !type:RoleTimeRequirement
            role: JobBorg
            time: 14400  # 4 hours
          - !type:OverallPlaytimeRequirement
            time: 36000 # 10 hours overall playtime
        alternativeRequirements:
          - !type:RoleTimeRequirement
            role: JobStationAi
            time: 14400  # 4 hours
    Borg:
      - !type:OverallPlaytimeRequirement
        time: 0
    Bartender:
      - !type:OverallPlaytimeRequirement
        time: 0
    Chef:
      - !type:OverallPlaytimeRequirement
        time: 0
    Scientist:
      - !type:OverallPlaytimeRequirement
        time: 0
    Roboticist:
      - !type:OverallPlaytimeRequirement
        time: 0
    SalvageLead:
      - !type:RoleTimeRequirement
        role: JobSalvageSpecialist
        time: 7200 # 2 hours
      - !type:OverallPlaytimeRequirement
        time: 21600  # 6 hours
    SalvageSpecialist:
      - !type:OverallPlaytimeRequirement
        time: 14400  # 4 hours
    MiningSpecialist:
      - !type:OverallPlaytimeRequirement
        time: 0
    Botanist:
      - !type:OverallPlaytimeRequirement
        time: 0
    Clown:
      - !type:OverallPlaytimeRequirement
        time: 0
    CargoTechnician:
      - !type:OverallPlaytimeRequirement
        time: 0
    TechnicalAssistant:
      - !type:OverallPlaytimeRequirement
        time: 0
    MedicalIntern:
      - !type:OverallPlaytimeRequirement
        time: 0
    ResearchAssistant:
      - !type:OverallPlaytimeRequirement
        time: 0
    Chaplain:
      - !type:OverallPlaytimeRequirement
        time: 0
    Janitor:
      - !type:OverallPlaytimeRequirement
        time: 0
    Lawyer:
      - !type:OverallPlaytimeRequirement
        time: 0
    Librarian:
      - !type:OverallPlaytimeRequirement
        time: 0
    Mime:
      - !type:OverallPlaytimeRequirement
        time: 0
    Musician:
      - !type:OverallPlaytimeRequirement
        time: 0
    ServiceWorker:
      - !type:OverallPlaytimeRequirement
        time: 0
    Visitor:
      - !type:OverallPlaytimeRequirement
        time: 0

#region Shortcut
#Easy Time Allocation

# 72000 # 20 hours
# 36000 # 10 hours
# 21600 # 6 hours
# 14400 # 4 Hours
# 7200 # 2 hours
# 3600 # 1 hour
# 0
