#region Base

- type: latheRecipe
  abstract: true
  id: BaseVehiclePartsRecipe
  completetime: 6
  categories:
  - LatheVehicleParts

#region Weapons
- type: latheRecipe
  parent: BaseGoldBorgModuleRecipe
  id: BorgModuleLaserCarbine
  result: BorgModuleLaserCarbine

- type: latheRecipe
  parent: CyborgEndoskeleton
  id: SecborgEndoskeleton
  result: SecborgEndoskeleton

- type: latheRecipePack
  id: FarHorizonsSecBorgRecipePack
  recipes:
  - SecborgEndoskeleton
  - BorgModuleLaserCarbine

- type: latheRecipe
  parent: CyborgEndoskeletonNS
  id: SecborgEndoskeletonNS
  result: SecborgEndoskeletonNS

- type: latheRecipePack
  id: FarHorizonsSecBorgRecipePackNS
  recipes:
  - SecborgEndoskeletonNS
  - BorgModuleLaserCarbine

- type: latheRecipe
  parent: BaseWeaponRecipeSidearm
  id: WeaponLaserPistol
  result: WeaponLaserPistol
  materials:
    Steel: 1000
    Glass: 400
    Plastic: 250

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserShotgun
  result: WeaponLaserShotgun
  materials:
    Steel: 2000
    Glass: 800
    Plastic: 800
    Plasma: 100

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: SmokeGrenade
  result: SmokeGrenade # Can't really mix reagents in a recipe. It's a bunch of smoke so should be simple
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 600
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: GrenadeStinger
  result: GrenadeStinger # Rubber.
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 600
    Plastic: 800

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: GrenadeFlashBang
  result: GrenadeFlashBang
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 600
    Plastic: 200

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: ClusterBangFull
  result: ClusterBangFull # x3
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 1800
    Plastic: 600
    Silver: 10

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: TearGasGrenade # Teargas is effectively a better smoke grenade, slap some silver on it.
  result: TearGasGrenade
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 800
    Plastic: 500
    Silver: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: ExGrenade
  result: ExGrenade
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 800
    Plastic: 500
    Plasma: 100
    Silver: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: GrenadeShrapnel
  result: GrenadeShrapnel # Explodes in frags, should need more metal. Also the "better" option for sec to use since it doesn't space.
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 1000
    Plastic: 500
    Plasma: 50
    Silver: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: EmpGrenade # EXCEEDINGLY lethal to a good chunk of the station, needs to be expensive.
  result: EmpGrenade
  categories:
  - Weapons
  completetime: 4
  materials:
    Steel: 800
    Plastic: 800
    Plasma: 100
    Uranium: 100
    Silver: 200
    Gold: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLeverActionNT
  result: WeaponLeverActionNT
  categories:
    - Weapons
  materials:
    Steel: 1200
    Plastic: 1000
#Attachements
    Glass: 100
    Silver: 10
    Gold: 10

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLeverActionNS
  result: WeaponLeverActionNS
  categories:
    - Weapons
  materials:
    Steel: 1400
    Plastic: 1000
#Attachements
    Glass: 150

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLeverActionModel2325
  result: WeaponLeverActionModel2325
  categories:
    - Weapons
  materials: #Cost is split between harder to obtain resources
    Steel: 600
    Plastic: 600
    Plasteel: 600
    Wood: 600
#Hardlight Internals
    Glass: 200
    Silver: 100
    Gold: 100

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponLeverActionModel2325Pistol
  result: WeaponLeverActionModel2325Pistol
  categories:
    - Weapons
  materials:
    Steel: 300
    Plastic: 300
    Plasteel: 300
    Wood: 300
#Hardlight Internals
    Glass: 100
    Silver: 50
    Gold: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: WeaponRevolverIndomitable
  result: WeaponRevolverIndomitable
  categories:
    - Weapons
  materials:
    Steel: 300
    Plastic: 300
    Plasteel: 300
    Wood: 300
#Hardlight Internals
    Glass: 100
    Silver: 50
    Gold: 50

- type: latheRecipe
  parent: BaseWeaponRecipe
  id: SpeedLoaderMagnumLeverEmptyHardlight
  result: SpeedLoaderMagnumLeverEmptyHardlight
  categories:
    - Weapons
  materials:
    Steel: 100
    Plastic: 100
    Plasteel: 100
#Hardlight Internals
    Glass: 50
    Silver: 10
    Gold: 10

#region Vehicles
- type: latheRecipe
  parent: BaseVehiclePartsRecipe
  id: LightArmorKit
  result: LightArmorKit
  categories:
  - LatheVehicleParts
  materials:
    ReinforcedGlass: 1000
    Steel: 500
    Plastic: 500

- type: latheRecipe
  parent: BaseVehiclePartsRecipe
  id: SecSiren
  result: SecSiren
  categories:
  - LatheVehicleParts
  materials:
    Glass: 500
    Steel: 250
    Plastic: 1000

#region Bags
- type: latheRecipe
  parent: BaseSoftPouchRecipe
  id: SoftPouchSecurity
  result: SoftPouchSecurity

- type: latheRecipe
  parent: BaseHardPouchRecipe
  id: HardPouchSecurity
  result: HardPouchSecurity