## Static

- type: latheRecipePack
  id: NSServiceBoardsStatic
  recipes:
  - BiogeneratorMachineCircuitboard
  - NSUniformPrinterMachineCircuitboard
  - MicrowaveMachineCircuitboard
  - OvenMachineCircuitboard
  - StoveMachineCircuitboard
  - ReagentGrinderMachineCircuitboard
  - ElectricGrillMachineCircuitboard
  - BoozeDispenserMachineCircuitboard
  - SodaDispenserMachineCircuitboard
  - SmartFridgeCircuitboard


## Dynamic

- type: latheRecipePack
  id: NSServiceBoards
  recipes:
  - BiofabricatorMachineCircuitboard
  - FatExtractorMachineCircuitboard
  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
  - SeedExtractorMachineCircuitboard # ^
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
  - SlopDispenserMachineCircuitboard #SL