using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._FarHorizons.Banking;
using Content.Shared._FarHorizons.Banking.Components;

namespace Content.Client._FarHorizons.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class FrontierBankUiFragment : BoxContainer
{
    private TransferInProgressState _transferInProgress = TransferInProgressState.None;
    private int? _cachedBankLimit;
    private int? _cachedCredstickLimit;

    public Action<int>? WithdrawRequest;
    public Action<int>? DepositRequest;

    public FrontierBankUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        DepositToCredstickButton.OnPressed += _ =>
        {
            _transferInProgress = TransferInProgressState.Deposit;
            TransferModalOverlay.Visible = true;
            TransferModalTitleLabel.Text = Loc.GetString("frontier-bank-deposit-to-credstick");

            TransferAmountInput.Text = "";
            TransferAmountInput.IsValid += v => int.TryParse(v, out var val) && val <= _cachedBankLimit;
        };

        WithdrawFromCredstickButton.OnPressed += _ =>
        {
            _transferInProgress = TransferInProgressState.Withdraw;
            TransferModalOverlay.Visible = true;
            TransferModalTitleLabel.Text = Loc.GetString("frontier-bank-withdraw-from-credstick");

            TransferAmountInput.Text = "";
            TransferAmountInput.IsValid += v => int.TryParse(v, out var val) && val <= _cachedCredstickLimit;
        };

        TransferConfirmButton.OnPressed += _ => ConfirmTransfer();

        TransferCancelButton.OnPressed += _ => CancelTransfer();
    }

    public void Populate(FrontierBankUiState state)
    {
        _transferInProgress = TransferInProgressState.None;

        if (state.OwnerName is {} name)
            AccountOwnerLabel.Text = Loc.GetString("frontier-bank-owner-text", ("name", name));
        BalanceAmountLabel.Text = Loc.GetString("frontier-bank-balance-text", ("balance", state.Balance.Balance));
        var limit = SharedBankingSystem.GetRemainingLimit(state.Balance);
        DailyLimitLabel.Text = Loc.GetString("frontier-bank-daily-limit-text", ("limit", limit));

        _cachedBankLimit = limit;
        _cachedCredstickLimit = state.CredstickBalance;

        if (state.CredstickBalance == null)
        {
            NoCredstickContainer.Visible = true;
            CredstickOperationsContainer.Visible = false;
            return;
        }

        NoCredstickContainer.Visible = false;
        CredstickOperationsContainer.Visible = true;
        CredstickBalanceAmountLabel.Text = Loc.GetString("frontier-bank-balance-text", ("balance", state.CredstickBalance.Value));
    }

    private void ConfirmTransfer()
    {
        if (!int.TryParse(TransferAmountInput.Text, out var value))
        {
            CancelTransfer();
            return;
        }

        switch (_transferInProgress)
        {
            case TransferInProgressState.Deposit:
                DepositRequest?.Invoke(value);
                break;
            
            case TransferInProgressState.Withdraw:
                WithdrawRequest?.Invoke(value);
                break;
        }

        CancelTransfer();
    }

    private void CancelTransfer()
    {
        TransferModalOverlay.Visible = false;
        _transferInProgress = TransferInProgressState.None;
        TransferAmountInput.IsValid = null;
    }
}

public enum TransferInProgressState : byte
{
    None,
    Withdraw,
    Deposit
}