using Robust.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Shared._FarHorizons.Cargo;
using Content.Shared.Cargo.Prototypes;
using Robust.Shared.Prototypes;
using System.Linq;
using Content.Client.Cargo.UI;
using Robust.Client.GameObjects;
using Content.Shared.Cargo;
using Robust.Client.Graphics;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class GSLNowUiFragment : BoxContainer
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;
    [Dependency] private IGameTiming _timing = default!;
    private readonly SpriteSystem _sprite;

    private List<ProtoId<CargoMarketPrototype>> _markets = new();
    private List<ProtoId<CargoProductPrototype>> _catalogue = new();
    private readonly List<string> _categoryStrings = new();
    private string? _category;
    private ProtoId<CargoProductPrototype>? _product;
    private event Action<CargoProductRow?>? _onProductSelected;
    private TimeSpan _nextOrder = TimeSpan.Zero;

    public event Action<ProtoId<CargoProductPrototype>, string, string, string>? SubmitOrder;

    public GSLNowUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += _ => PopulateProducts();
        Categories.OnItemSelected += OnCategoryItemSelected;
        _onProductSelected += OnStartOrdering;
        OrderCancelButton.OnPressed += _ => OnCancelOrdering();
        OrderConfirmButton.OnPressed += _ => OnFinishOrdering();
        ErrorCloseButton.OnPressed += _ => ErrorModalOverlay.Visible = false;

        _sprite = _entMan.System<SpriteSystem>();
    }

    private static string FormatTimeLeft(TimeSpan timeSpan)
    {
        if (timeSpan < TimeSpan.Zero)
            timeSpan = TimeSpan.Zero;

        return timeSpan.TotalMinutes >= 1 ? $"{timeSpan:%m}m {timeSpan:%s}s" : $"{timeSpan:%s}s";
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        if (_nextOrder > _timing.CurTime)
        {
            var formattedTime = FormatTimeLeft(_nextOrder - _timing.CurTime);
            OrderTimeLeft.Text = Loc.GetString("gsl-now-next-order-time-left-text", ("time", formattedTime));
            return;
        }

        OrderTimeLeft.Text = Loc.GetString("gsl-now-next-order-none-text");
    }

    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetCategoryText(args.Id);
        PopulateProducts();
    }

    private void OnStartOrdering(CargoProductRow? val)
    {
        if (val == null ||
            val.Product == null)
            return;
        
        if (_nextOrder > _timing.CurTime)
        {
            ErrorModalOverlay.Visible = true;
            return;
        }

        OrderModalOverlay.Visible = true;
        _product = val.Product.ID;
    }

    private void OnCancelOrdering()
    {
        OrderModalOverlay.Visible = false;
        _product = null;
    }

    private void OnFinishOrdering()
    {
        OrderModalOverlay.Visible = false;

        if (_product == null)
            return;

        var recipient = RecipientInput.Text;
        var station = StationInput.Text;
        var instructions = InstructionsInput.Text;

        SubmitOrder?.Invoke(_product.Value, recipient, station, instructions);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoryStrings[id];
        Categories.SelectId(id);
    }

    public void Populate(GSLNowUiState state)
    {
        _markets = state.Markets;
        _catalogue = state.Products;
        _nextOrder = state.NextOrder;
        PopulateCategories();
        PopulateProducts();
        PopulateOrders(state.Orders);

        RecipientInput.Text = state.DeliveryName;
        StationInput.Text = state.DeliveryStation;
    }

    private IEnumerable<CargoProductPrototype> ProductPrototypes
    {
        get
        {
            foreach (var cargoPrototypeId in _catalogue)
            {
                var cargoPrototype = _protoMan.Index(cargoPrototypeId);

                if (!_markets?.Contains(cargoPrototype.Group) ?? false)
                    continue;

                yield return cargoPrototype;
            }
        }
    }

    public void PopulateCategories()
    {
        _categoryStrings.Clear();
        Categories.Clear();

        foreach (var prototype in ProductPrototypes)
        {
            if (!_categoryStrings.Contains(Loc.GetString(prototype.Category)))
            {
                _categoryStrings.Add(Loc.GetString(prototype.Category));
            }
        }

        _categoryStrings.Sort();

        // Add "All" category at the top of the list
        _categoryStrings.Insert(0, Loc.GetString("cargo-console-menu-populate-categories-all-text"));

        foreach (var str in _categoryStrings)
        {
            Categories.AddItem(str);
        }
    }

    public void PopulateOrders(IEnumerable<CargoOrderData> orders)
    {
        OrdersContainer.RemoveAllChildren();

        foreach (var order in orders)
        {
            // Resolve prototype data for the ordered product
            if (!_protoMan.Resolve(order.Product, out var productProto))
                continue;

            var product = _protoMan.Index<EntityPrototype>(productProto.Product);
            var productName = productProto.Name;
            var requester = !string.IsNullOrEmpty(order.Requester) 
                ? order.Requester 
                : Loc.GetString("cargo-console-menu-order-row-alerts-requester-unknown");
            
            var account = _protoMan.Index(order.Account);

            // Determine status and set appropriate visual indicators
            var isPending = !order.Approved;
            var statusLocKey = isPending ? "gsl-now-order-status-pending" : "gsl-now-order-status-in-delivery";

            if (order.PersonalDeliverySuccess != null)
                statusLocKey = order.PersonalDeliverySuccess.Value ? "gsl-now-order-status-delivery-success" : "gsl-now-order-status-delivery-fail";

            var row = new CargoOrderRow
            {
                Order = order,

                Title =
                {
                    Text = Loc.GetString(
                        "cargo-console-menu-personal-order-row-title",
                        ("productName", productName),
                        ("orderPrice", MathF.Floor(productProto.Cost * productProto.CreditCost))),
                },

                Stride =
                {
                    PanelOverride = new StyleBoxFlat
                    {
                        ContentMarginBottomOverride = 2,
                    },
                },

                Icon = { Texture = _sprite.Frame0(product) },

                ProductName =
                {
                    Text = Loc.GetString(statusLocKey),
                },
            };

            row.Cancel.Visible = false;
            row.Approve.Visible = false;

            OrdersContainer.AddChild(row);
        }
    }

    public void PopulateProducts()
    {
        Products.RemoveAllChildren();
        var products = ProductPrototypes.ToList();
        products.Sort((x, y) =>
            string.Compare(x.Name, y.Name, StringComparison.CurrentCultureIgnoreCase));

        var search = SearchBar.Text.Trim().ToLowerInvariant();
        foreach (var prototype in products)
        {
            // if no search or category
            // else if search
            // else if category and not search
            if (search.Length == 0 && _category == null ||
                search.Length != 0 && prototype.Name.ToLowerInvariant().Contains(search) ||
                search.Length != 0 && prototype.Description.ToLowerInvariant().Contains(search) ||
                search.Length == 0 && _category != null && Loc.GetString(prototype.Category).Equals(_category))
            {
                var button = new CargoProductRow
                {
                    Product = prototype,
                    ProductName = { Text = prototype.Name },
                    MainButton = { ToolTip = prototype.Description },
                    PointCost = { Text = Loc.GetString("gsl-now-cost-amount", ("amount", Math.Floor(prototype.Cost * prototype.CreditCost).ToString())) },
                    Icon = { Texture = _sprite.Frame0(prototype.Icon) },
                };
                button.MainButton.OnPressed += args =>
                {
                    _onProductSelected?.Invoke(button);
                };
                Products.AddChild(button);
            }
        }
    }
}