using Content.Client.UserInterface.Controls;
using Content.Shared.Item.ItemToggle.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._FarHorizons.CoolingUnit;

[GenerateTypedNameReferences]
public sealed partial class CoolingUnitWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;

    public FloatSpinBox TemperatureSpinbox;

    public EntityUid Entity;

    public CoolingUnitWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SpinboxHBox.AddChild(
            TemperatureSpinbox = new FloatSpinBox(.1f, 2) { MinWidth = 150, HorizontalExpand = true }
            );
    }

    public void SetActive(bool active)
        => ToggleStatusButton.Pressed = active;

    public void SetTemperature(float temperature)
        => TemperatureSpinbox.Value = temperature;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_entManager.TryGetComponent(Entity, out ItemToggleComponent? toggle))
        {
            SetActive(toggle.Activated);
        }
    }
}
