using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Timing;
using Robust.Shared.Containers;
using Content.Shared._FarHorizons.PowerArmor;
using Content.Shared.Wires;
using Content.Shared.Power.Components;
using System.Linq;
using Content.Shared.Power.EntitySystems;
using Content.Shared.Damage.Systems;
using Content.Shared.Damage.Components;
using Robust.Client.UserInterface.Controls;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using System.Numerics;
using Robust.Shared.Prototypes;
using Content.Shared.Body;
using Robust.Client.ResourceManagement;
using Robust.Client.GameObjects;
using Content.Shared._FarHorizons.LimbDamage.Components;
using Content.Shared._FarHorizons.LimbDamage;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.PowerCell.Components;

namespace Content.Client._FarHorizons.PowerArmor.UI;

[GenerateTypedNameReferences]
public sealed partial class PowerArmorMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private readonly SharedContainerSystem _container;
    private readonly SharedBatterySystem _battery;
    private readonly DamageableSystem _damageable;
    private readonly LimbDamageSystem _limbDamage;
    private readonly IPrototypeManager _prototypes;
    private readonly IResourceCache _cache;
    private readonly SpriteSystem _spriteSystem;

    private EntityUid _entity;
    private EntityUid? _entityWearer;
    private int _currComplexity = 0;
    private int _maxComplexity = 0;
    private readonly Dictionary<PowerArmorVisualLayers, EntityUid?> _parts = new();
    private readonly Dictionary<PowerArmorVisualLayers, PartControls> _partControls = new();
    private PartControls? _openDetails;
    private float _updateTimer;
    public event Action<PowerArmorVisualLayers, NetEntity>? OnUninstallPart;
    public event Action? OnTogglePowerArmor;
    private readonly record struct PartControls(
        Button PartButton,
        RichTextLabel PartButtonLabel,
        TextureRect PartButtonArrow,
        ProgressBar Bar,
        RichTextLabel Percent,
        BoxContainer Details,
        RichTextLabel Description,
        Button UninstallButton,
        StyleBoxFlat BarForeground);

    private readonly HashSet<EntityUid> _moduleEntities = new();
    private readonly Dictionary<EntityUid, ModuleControls> _moduleControls = new();
    private ModuleControls? _openDetailsModules;
    private readonly Dictionary<ProtoId<DamageGroupPrototype>, Button> _damageGroupButtons = new();
    public event Action<NetEntity>? OnUninstallModule;
    public event Action<NetEntity>? OnToggleModule;
    private ProtoId<OrganCategoryPrototype> _currTarget = "Torso";
    private readonly static ProtoId<OrganCategoryPrototype> _defaultLimb = "Torso";
    private readonly StyleBoxFlat _chargeBarForeground = new();
    private readonly record struct ModuleControls(
        PanelContainer Panel,
        Button ModuleButton,
        TextureRect PartButtonArrow,
        Button PowerToggle,
        Button Uninstall,
        Button IdleDrain, 
        Button ActiveDrain,
        Button OnUseDrain,
        Button Complexity,
        BoxContainer Details,
        RichTextLabel Description);
    public PowerArmorMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _container = _entityManager.System<SharedContainerSystem>();
        _battery = _entityManager.System<SharedBatterySystem>();
        _damageable = _entityManager.System<DamageableSystem>();
        _limbDamage = _entityManager.System<LimbDamageSystem>();
        _spriteSystem = _entityManager.System<SpriteSystem>();

        var dependencies = IoCManager.Instance!;
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();

        _parts = new()
        {
            [PowerArmorVisualLayers.Head] = null,
            [PowerArmorVisualLayers.Chest] = null,
            [PowerArmorVisualLayers.RArm] = null,
            [PowerArmorVisualLayers.LArm] = null,
            [PowerArmorVisualLayers.RLeg] = null,
            [PowerArmorVisualLayers.LLeg] = null,
        };

        var panelsByLayer = new Dictionary<PowerArmorVisualLayers, PanelContainer>
        {
            [PowerArmorVisualLayers.Head] = Head,
            [PowerArmorVisualLayers.Chest] = Chest,
            [PowerArmorVisualLayers.RArm] = RArm,
            [PowerArmorVisualLayers.LArm] = LArm,
            [PowerArmorVisualLayers.RLeg] = RLeg,
            [PowerArmorVisualLayers.LLeg] = LLeg,
        };

        foreach (var (layer, panel) in panelsByLayer)
        {
            var controls = GeneratePanel(panel);
            _partControls[layer] = controls;

            controls.PartButton.OnPressed += _ => ToggleContainer(_partControls[layer], _parts[layer]);
            controls.UninstallButton.OnPressed += _ =>
            {
                if (_parts[layer] is { } part)
                    OnUninstallPart?.Invoke(layer, _entityManager.GetNetEntity(part));
            };
        }

        ActivationButton.OnPressed += _ => OnTogglePowerArmor?.Invoke();
        LimbTargettingDisplay.OnSelectedLimb += SetLimbTarget;

        UnpoweredOverlay.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(0f, 0f, 0f, 0.6f)
        };

        ChargeBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.DimGray };
        ChargeBar.ForegroundStyleBoxOverride = _chargeBarForeground;
    }

    public void SetEntity(EntityUid entity)
    {
        _entity = entity;
        if(!_entityManager.TryGetComponent<PowerArmorComponent>(_entity, out var PAComp)) return;
        
        _maxComplexity = PAComp.MaxComplexity;
        
        if(PAComp.Wearer != null)
            _entityWearer = PAComp.Wearer.Value;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _updateTimer -= args.DeltaSeconds;

        if (_updateTimer > 0)
            return;

        _updateTimer = 0.1f;
        UpdateWindow();
    }

    private void SetLimbTarget(ProtoId<OrganCategoryPrototype> target)
    {
        _currTarget = target;
        LimbTargettingDisplay.UpdateLimb(_currTarget);
        UpdateWindow();
    }

    public void UpdateWindow()
    {
        if(_container.TryGetContainer(_entity, "cell_slot", out var cellSlot) 
        && cellSlot.ContainedEntities.Count != 0
        && _entityManager.TryGetComponent<BatteryComponent>(cellSlot.ContainedEntities.First(), out var battery))
        {
            var charge = (int)Math.Round(_battery.GetChargeLevel((cellSlot.ContainedEntities.First(), battery)) * 100f); 
            ChargePercent.Text = $"{charge}%";
            ChargeBar.Value = charge;
            _chargeBarForeground.BackgroundColor = Color.InterpolateBetween(Color.Red, Color.Green, charge / 100f);

            ChargePercent.ModulateSelfOverride = Color.White;
        }
        else
        {
            ChargeBar.Value = 0;
            ChargePercent.Text = "Power Cell Missing.";
            ChargePercent.ModulateSelfOverride = Color.Red;
        }

        if(_entityManager.TryGetComponent<WiresPanelComponent>(_entity, out var wirePanel))
        {
            PanelStatus.Text = wirePanel.Open ? "Open" : "Closed";
            PanelStatus.ModulateSelfOverride = wirePanel.Open ? Color.LimeGreen : Color.Red;
        }

        if (!_entityManager.TryGetComponent<PowerArmorComponent>(_entity, out var paComp))
            return;

        ActivationButton.ModulateSelfOverride = paComp.IsPowered ? Color.Green : null;
        foreach (var layer in _parts.Keys.ToList())
            if (paComp.Parts.TryGetValue(layer, out var part)) _parts[layer] = part;

        if (_entityManager.EntityExists(paComp.OtherHalf) && _entityManager.TryGetComponent<PowerArmorComponent>(paComp.OtherHalf, out var paComp2))
            if (paComp2.Parts.TryGetValue(PowerArmorVisualLayers.Head, out var headPart)) _parts[PowerArmorVisualLayers.Head] = headPart;
    

        foreach (var (layer, controls) in _partControls)
            UpdateParts(controls, _parts[layer]);

        UpdateModules();

        _entityWearer = paComp.Wearer;
        if (_entityWearer != null && paComp.IsPowered)
        {
            if (!_entityManager.TryGetComponent<LimbDamageableComponent>(_entityWearer, out var limbDamageable))
            {
                NoUserLabel.Text = "NO USER DETECTED";
                UnpoweredOverlay.Visible = true;
                return;
            }

            ProtoId<LimbTargettingPrototype> limbTargetVisuals = "LimbTargetHuman";
            limbTargetVisuals = limbDamageable.Proto;

            LimbTargettingDisplay.InitTarget(_prototypes, _cache, _spriteSystem, limbTargetVisuals);
            LimbTargettingDisplay.Visible = true;
            LimbTargettingDisplay.ModulateSelfOverride = null;

            var fullBodyDamage = _limbDamage.TryGetFullBodyDamage(_entityWearer.Value);
            var fullBodyDamageGroups = _limbDamage.TryGetFullBodyDamageGroups(_entityWearer.Value);

            if (fullBodyDamage == null || fullBodyDamageGroups == null)
                return;

            if (!fullBodyDamage.ContainsKey(_currTarget))
                _currTarget = _defaultLimb;

            LimbTargettingDisplay.SetHealth(fullBodyDamage.ToDictionary(p => p.Key, p => p.Value.Sum(e => (float)e.Value)));
            IReadOnlyDictionary<ProtoId<DamageTypePrototype>, FixedPoint2> damagePerType = fullBodyDamage[_currTarget];
        
            var groupOrder = new List<string> { "Burn", "Brute", "Airloss", "Toxin", "Genetic" };
            var sortedGroups = fullBodyDamageGroups[_currTarget]
                .OrderBy(g => groupOrder.IndexOf(g.Key))
                .ToDictionary(g => g.Key, g => g.Value);

            UpdateDamageInfo(sortedGroups);
            DamageInfoPanel.Visible = true;

            UnpoweredOverlay.Visible = false;
        }
        else
        {
            NoUserLabel.Text = paComp.IsPowered ? "NO USER DETECTED" : "SUIT UNPOWERED";
            UnpoweredOverlay.Visible = true;
            LimbTargettingDisplay.Visible = false;
            LimbTargettingDisplay.ModulateSelfOverride = Color.White.WithAlpha(0.3f);
            DamageInfoPanel.Visible = false;
        }
        if(_entityManager.TryGetComponent<PowerCellDrawComponent>(_entity, out var pcdComp))
            PowerDrain.Text = $"Total Power Drain: {pcdComp.DrawRate}";
    }

    private void AddModulePanel(EntityUid module)
    {
        if(!_entityManager.TryGetComponent<PowerArmorModuleComponent>(module, out var moduleComp))
            return;

        var row = new PanelContainer
        {
            Name = $"{module}",
            StyleClasses = { "BackgroundPanel" },
            Margin = new Thickness(10, 5, 10, 0)
        };

        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var powerButton = new Button
        {
            Name = $"{module}-Toggle",
            StyleClasses = { "ButtonSquare" },
            Margin = new Thickness(0, 2, 2, 2),
            SetSize = new Vector2(32),
            Disabled = !moduleComp.canBeToggled
        };

        var powerTexture = new TextureRect
        {
            TexturePath = "/Textures/Interface/VerbIcons/Spare/poweronoff.svg.192dpi.png",
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            SetSize = new Vector2(16)
        };
        powerButton.AddChild(powerTexture);

        box.AddChild(powerButton);

        var uninstallButton = new Button
        {
            Name = $"{module}-Uninstall",
            StyleClasses = { "ButtonSquare" },
            Margin = new Thickness(0, 2, 2, 2),
            SetSize = new Vector2(32)
        };

        var uninstallTexture = new TextureRect
        {
            TexturePath = "/Textures/Interface/VerbIcons/drop.svg.192dpi.png",
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            SetSize = new Vector2(20)
        };
        uninstallButton.AddChild(uninstallTexture);

        box.AddChild(uninstallButton);

        var moduleNameButton = new Button
        {
            Name = $"{module}-Label",
            StyleClasses = { "ButtonSquare" },
            Margin = new Thickness(0, 2, 2, 2),
            HorizontalExpand = true
        };

        var moduleNamecontainer = new BoxContainer
        {
            HorizontalAlignment = HAlignment.Left
        };

        var moduleNameArrow = new TextureRect
        {
            StyleClasses = new StyleClassCollection("ButtonSquare"),
            TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png",
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            SetSize = new Vector2(16, 16),
            Margin = new Thickness(0, 2, 4, 0)
        };
        moduleNamecontainer.AddChild(moduleNameArrow);

        var moduleNameLabel = new RichTextLabel
        {
            Text = _entityManager.TryGetComponent<MetaDataComponent>(module, out var meta)
                ? meta.EntityName
                : "Unknown Module",
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center
        };
        moduleNamecontainer.AddChild(moduleNameLabel);

        moduleNameButton.AddChild(moduleNamecontainer);
        box.AddChild(moduleNameButton);

        var idleDrainbutton = new Button
        {
            Name = $"{module}-IdleDrain",
            StyleClasses = { "ButtonSquare" },
            Text = $"{moduleComp.IdlePowerDrain}",
            Margin = new Thickness(0, 2, 2, 2),
            SetSize = new Vector2(32),
            Disabled = true
        };

        box.AddChild(idleDrainbutton);

        var activeDrainButton = new Button
        {
            Name = $"{module}-ActiveDrain",
            StyleClasses = { "ButtonSquare" },
            Text = $"{moduleComp.ActivePowerDrain}",
            Margin = new Thickness(0, 2, 2, 2),
            SetSize = new Vector2(32),
            Disabled = true
        };

        box.AddChild(activeDrainButton);
        
        var onUseDrainButton = new Button
        {
            Name = $"{module}-OnUseDrain",
            StyleClasses = { "ButtonSquare" },
            Text = "0",
            Margin = new Thickness(0, 2, 2, 2),
            SetSize = new Vector2(32),
            Disabled = true
        };

        box.AddChild(onUseDrainButton);

        var complexityButton = new Button
        {
            Name = $"{module}-Complexity",
            StyleClasses = { "ButtonSquare" },
            Text = $"{moduleComp.ComplexityCost}",
            Margin = new Thickness(0, 2, 2, 2),
            SetSize = new Vector2(32),
            Disabled = true
        };

        var mainBoxContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };
        mainBoxContainer.AddChild(box);

        var detailsBox = new BoxContainer
        {
            Name = $"{module}Details",
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Visible = false,
            Margin = new Thickness(10, 5, 10, 5)
        };

        var detailsDivider = new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            SetHeight = 1,
            Margin = new Thickness(0, 0, 0, 5)
        };
        detailsBox.AddChild(detailsDivider);

        var descriptionLabel = new RichTextLabel
        {
            Name = $"{module}Description",
            Text = _entityManager.TryGetComponent<MetaDataComponent>(module, out var descMeta)
                ? descMeta.EntityDescription
                : string.Empty,
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(10, 0),
            MaxWidth = 480
        };
        detailsBox.AddChild(descriptionLabel);

        mainBoxContainer.AddChild(detailsBox);
        row.AddChild(mainBoxContainer);
        ModulesPanel.AddChild(row);

        _moduleControls[module] = new ModuleControls(row, moduleNameButton, moduleNameArrow, powerButton, uninstallButton, idleDrainbutton, activeDrainButton, onUseDrainButton, complexityButton, detailsBox, descriptionLabel);

        var netModule = _entityManager.GetNetEntity(module);

        powerButton.OnPressed += _ => OnToggleModule?.Invoke(netModule);
        uninstallButton.OnPressed += _ => OnUninstallModule?.Invoke(netModule);
        moduleNameButton.OnPressed += _ => ToggleModuleDescription(_moduleControls[module]);

        UpdateModuleButtonColor(module);
    }

    private void UpdateModuleButtonColor(EntityUid module)
    {
        if (!_moduleControls.TryGetValue(module, out var controls))
            return;

        if (!_entityManager.TryGetComponent<PowerArmorModuleComponent>(module, out var moduleComp))
            return;

        controls.PowerToggle.ModulateSelfOverride = moduleComp.isEnabled ? Color.LimeGreen : null;
    }

    private void RemoveModulePanel(EntityUid module)
    {
        if (!_moduleControls.Remove(module, out var controls))
            return;

        ModulesPanel.RemoveChild(controls.Panel);
    }

    private void UpdateModules()
    {
        if (!_container.TryGetContainer(_entity, "modules", out var moduleSlot))
            return;

        foreach (var module in moduleSlot.ContainedEntities)
        {
            if(!_entityManager.TryGetComponent<PowerArmorModuleComponent>(module, out var moduleComp))
                continue;

            if (_moduleEntities.Contains(module))
            {
                UpdateModuleButtonColor(module);
                continue;
            }

            _currComplexity+=moduleComp.ComplexityCost;
            _moduleEntities.Add(module);
            AddModulePanel(module);
        }

        foreach (var tracked in _moduleEntities.ToList())
        {
            if(!_entityManager.TryGetComponent<PowerArmorModuleComponent>(tracked, out var moduleComp))
                continue;

            if (moduleSlot.ContainedEntities.Contains(tracked))
                continue;

            _currComplexity-=moduleComp.ComplexityCost;
            RemoveModulePanel(tracked);
            _moduleEntities.Remove(tracked);
        }

        ModulesComplexity.Text = $"{_currComplexity} of {_maxComplexity} complexity used";
    }

    private void UpdateParts(PartControls controls, EntityUid? part)
    {
        if (part != null)
        {
            if (!_entityManager.TryGetComponent<PowerArmorPartComponent>(part.Value, out var papComp))
                return;

            if (_entityManager.TryGetComponent<MetaDataComponent>(part.Value, out var metaData))
            {
                controls.PartButtonLabel.Text = metaData.EntityName;
                controls.PartButton.Disabled = false;
                controls.Description.Text = metaData.EntityDescription;
            }
            else
            {
                controls.PartButton.Text = "Empty";
                controls.PartButton.Disabled = true;
            }

            if (_entityManager.TryGetComponent<DamageableComponent>(part.Value, out var damageComp))
            {
                var integrity = Math.Clamp((int) ((papComp.MaxIntegrity - _damageable.GetPositiveDamage((part.Value, damageComp)).GetTotal()) / papComp.MaxIntegrity * 100), 0, 100);
                controls.Bar.Value = integrity;
                controls.BarForeground.BackgroundColor = Color.InterpolateBetween(Color.Red, Color.Green, integrity / 100f);

                controls.Bar.Visible = true;
                controls.Percent.Text = $"{integrity}%";
                controls.Percent.Visible = true;
            }
            else
            {
                controls.Bar.Visible = false;
                controls.Percent.Visible = false;
            }
        }
        else
        {
            controls.PartButtonLabel.Text = "Empty";
            controls.PartButton.Disabled = true;
            controls.Bar.Visible = false;
            controls.Percent.Visible = false;

            if (controls.Details.Visible)
                controls.Details.Visible = false;
            if (_openDetails == controls)
                _openDetails = null;
        }
    }

    private void UpdateDamageInfo(Dictionary<ProtoId<DamageGroupPrototype>, FixedPoint2> groups)
    {
        foreach (var (key, value) in groups)
        {
            if (_damageGroupButtons.TryGetValue(key, out var button))
            {
                button.Text = $"{key}: {value} ";
            }
            else
            {
                var newButton = new Button
                {
                    Text = $"{key}: {value} ",
                    Disabled = true,
                    MaxWidth = 120
                };
                DamageInfo.AddChild(newButton);
                _damageGroupButtons[key] = newButton;
            }
        }

        foreach (var damageGroup in _damageGroupButtons.Keys.ToList())
        {
            if (groups.TryGetValue(damageGroup, out var value) && value > 0)
                continue;

            DamageInfo.RemoveChild(_damageGroupButtons[damageGroup]);
            _damageGroupButtons.Remove(damageGroup);
        }

        if(_damageGroupButtons.Count() == 0)
            NoDamageDetected.Visible = true;
        else
            NoDamageDetected.Visible = false;
    }

    private PartControls GeneratePanel(PanelContainer panel)
    {
        var MainBoxContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        var PartNameIntegrityBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Name = $"{panel.Name}Row",
            HorizontalExpand = true,
            SetHeight = 30
        };

        var PartTypeLabel = new RichTextLabel
        {
            Text = $"{panel.Name}: ",
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center,
            MinSize = new Vector2(60, 0)
        };

        PartNameIntegrityBox.AddChild(PartTypeLabel);

        var PartNameButton = new Button
        {
            StyleClasses = { "CrossButtonRed" },
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center,
            MinWidth = 350
        };

        var PartNameBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalExpand = true
        };

        var PartNameArrow = new TextureRect
        {
            StyleClasses = new StyleClassCollection("ButtonSquare"),
            TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png",
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            SetSize = new Vector2(16, 16),
            Margin = new Thickness(0, 2, 4, 0)
        };
        PartNameBox.AddChild(PartNameArrow);

        var PartNameLabel = new RichTextLabel
        {
            Name = $"{panel.Name}Label",
            Text="Emtpty",
            HorizontalAlignment = HAlignment.Left,
            VerticalAlignment = VAlignment.Center
        };
        PartNameBox.AddChild(PartNameLabel);

        PartNameButton.AddChild(PartNameBox);
        PartNameIntegrityBox.AddChild(PartNameButton);

        var PartIntegrityControl = new Control
        {
            HorizontalExpand = true,
            Margin = new Thickness(5, 0, 5, 0)
        };

        var PartIntegrityBar = new ProgressBar
        {
            Name = $"{panel.Name}Bar",
            MinValue = 0,
            MaxValue = 100,
            Value = 50,
            SetHeight = 25
        };

        var barForeground = new StyleBoxFlat();
        PartIntegrityBar.BackgroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.DimGray };
        PartIntegrityBar.ForegroundStyleBoxOverride = barForeground;
        
        PartIntegrityControl.AddChild(PartIntegrityBar);

        var PartPercentLabel = new RichTextLabel
        {
            Name = $"{panel.Name}Percent",
            Text = "50%",
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(5, 0, 0, 0)
        };
        PartIntegrityControl.AddChild(PartPercentLabel);

        PartNameIntegrityBox.AddChild(PartIntegrityControl);
        MainBoxContainer.AddChild(PartNameIntegrityBox);

        var DetailsBox = new BoxContainer
        {
            Name = $"{panel.Name}Details",
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Visible = false,
            Margin = new Thickness(10, 5, 10, 5)
        };

        var DetailsDivider = new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            SetHeight = 1,
            Margin = new Thickness(0, 0, 0, 5)
        };
        DetailsBox.AddChild(DetailsDivider);

        var DescriptionUninstallBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal
        };

        var DescriptionLabel = new RichTextLabel
        {
            Name = $"{panel.Name}Description",
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(10, 0),
            MaxWidth = 350
        };
        DescriptionUninstallBox.AddChild(DescriptionLabel);

        var spacingControl = new Control
        {
            HorizontalExpand = true
        };
        DescriptionUninstallBox.AddChild(spacingControl);

        var UninstallButton = new Button
        {
            Name = $"{panel.Name}UninstallButton",
            Text = "Uninstall",
            StyleClasses = { "CrossButtonRed" },
            HorizontalAlignment = HAlignment.Right,
            Margin = new Thickness(10,0, 0, 0)
        };
        DescriptionUninstallBox.AddChild(UninstallButton);

        DetailsBox.AddChild(DescriptionUninstallBox);
        MainBoxContainer.AddChild(DetailsBox);

        panel.AddChild(MainBoxContainer);

        return new PartControls(PartNameButton, PartNameLabel, PartNameArrow, PartIntegrityBar, PartPercentLabel, DetailsBox, DescriptionLabel, UninstallButton, barForeground);    
    }

    private void ToggleContainer(PartControls container, EntityUid? part)
    {
        if (part == null)
            return;

        if (_openDetails == container)
        {
            container.Details.Visible = false;
            container.PartButtonArrow.TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png"; 
            _openDetails = null;
            return;
        }

        if (_openDetails != null)
        {
            _openDetails.Value.Details.Visible  = false;
            _openDetails.Value.PartButtonArrow.TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png"; 
        }

        container.Details.Visible = true;
        container.PartButtonArrow.TexturePath = "/Textures/_FarHorizons/Interface/group90.svg.192dpi.png";
        _openDetails = container;
    }

    private void ToggleModuleDescription(ModuleControls container)
    {    
        if (_openDetailsModules == container)
        {
            container.Details.Visible = false;
            container.PartButtonArrow.TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png"; 
            _openDetailsModules = null;
            return;
        }

        if (_openDetailsModules != null)
        {
            _openDetailsModules.Value.Details.Visible  = false;
            _openDetailsModules.Value.PartButtonArrow.TexturePath = "/Textures/Interface/VerbIcons/group.svg.192dpi.png"; 
        }

        container.Details.Visible = true;
        container.PartButtonArrow.TexturePath = "/Textures/_FarHorizons/Interface/group90.svg.192dpi.png";
        _openDetailsModules = container;
    }
}