using System.Linq;
using System.Numerics;
using Content.Shared._FarHorizons.PowerArmor;
using Content.Shared.Body;
using Content.Shared.Damage.Components;
using Content.Shared.Damage.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._FarHorizons.PowerArmor.UI;

[GenerateTypedNameReferences]
public sealed partial class PowerArmorStatusDisplay : Control
{
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IEntityManager _entMan = default!;
    private DamageableSystem _damageable 
        => _entMan.System<DamageableSystem>();
    private static readonly ProtoId<ShaderPrototype> _shaderProto = "LimbTargetting";
    private Dictionary<ProtoId<OrganCategoryPrototype>, ShaderInstance> _shaders = new();

    private bool _shaderInitialized =>
        _shaders.Count > 0;

    public Dictionary<ProtoId<OrganCategoryPrototype>, DrawLimb> DrawLimbs = new();
    public List<DrawLabel> DrawLabels = new();
    public Vector3 DefaultColor = new(0f, 0f, 0f);
    public bool DrawDebugBoxes;

    public EntityUid _playerEntity;
    public Dictionary<ProtoId<OrganCategoryPrototype>, float> LimbDamage = new();

    public PowerArmorStatusDisplay()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void InitShaders(IPrototypeManager protoMan)
    {        
        var baseShader = protoMan.Index(_shaderProto).InstanceUnique();
        baseShader.SetParameter("outerColor", DefaultColor);
        baseShader.SetParameter("innerFill", true);
        baseShader.SetParameter("innerColor", DefaultColor);

        foreach (var key in DrawLimbs.Keys)
            _shaders[key] = baseShader.Duplicate();

        if (_player.LocalSession?.AttachedEntity is { } playerEnt)
            _playerEntity = playerEnt;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        if (!_shaderInitialized) return;

        UpdateShaders();

        foreach (var (limb, draw) in DrawLimbs.Reverse())
        {
            handle.UseShader(_shaders[limb]);

            foreach (var texture in draw.Textures)
                handle.DrawTextureRect(texture, UIBox2.FromDimensions(0, 0, Width * UIScale, Height * UIScale));

            handle.UseShader(null);

            if (!DrawDebugBoxes) continue;

            handle.DrawRect(
                new UIBox2(
                    new Vector2(draw.Area.Left * Width * UIScale, draw.Area.Top * Height * UIScale),
                    new Vector2(draw.Area.Right * Width * UIScale, draw.Area.Bottom * Height * UIScale)),
                    Color.Red, 
                    false
                );
        }

        foreach (var label in DrawLabels)
        {
            Vector2 pos = new(label.Position.X * Width * UIScale, label.Position.Y * Height * UIScale);
            Color col = new(DefaultColor.X, DefaultColor.Y, DefaultColor.Z);
            handle.DrawString(label.Font, pos, label.Text, col);
        }
    }

    private void UpdateShaders()
    {
        foreach (var (limb, shader) in _shaders)
        {
            var color = HealthColor(limb);

            shader.SetParameter("outerColor", new Vector3(1f, 1f, 1f));
            shader.SetParameter("innerColor", color);
        }
    }

    private Vector3 HealthColor(ProtoId<OrganCategoryPrototype> limb)
    {
        var powerArmorPart = OrganToPowerArmor(limb);

        if (!_entMan.TryGetComponent<PowerArmorUserComponent>(_playerEntity, out var PAUComp)
            || !_entMan.TryGetComponent<PowerArmorComponent>(PAUComp.Wearing, out var PAComp)
            || !_entMan.TryGetComponent<PowerArmorComponent>(PAComp.OtherHalf, out var PAOComp))
            return DefaultColor;

        var partsOwner = powerArmorPart == PowerArmorVisualLayers.Head ? PAOComp : PAComp;

        if (!partsOwner.Parts.TryGetValue(powerArmorPart, out var partUid)
            || partUid == null
            || !_entMan.TryGetComponent<PowerArmorPartComponent>(partUid, out var PAPComp)
            || PAPComp.isBroken
            || !_entMan.TryGetComponent<DamageableComponent>(partUid, out var damageableComp))
            return DefaultColor;
            

        var health = Math.Clamp(
            (int)((PAPComp.MaxIntegrity - _damageable.GetPositiveDamage((partUid.Value, damageableComp)).GetTotal()) / PAPComp.MaxIntegrity * 100),
            0, 100);

        var color = Color.InterpolateBetween(Color.Red, Color.Green, health / 100f);
        return new Vector3(color.R, color.G, color.B);
    }

    private PowerArmorVisualLayers OrganToPowerArmor(ProtoId<OrganCategoryPrototype> limb) 
    => (string)limb switch
    {
        "Torso" => PowerArmorVisualLayers.Chest,
        "Head" => PowerArmorVisualLayers.Head,
        "ArmLeft" => PowerArmorVisualLayers.RArm,
        "ArmRight" => PowerArmorVisualLayers.LArm,
        "LegLeft" => PowerArmorVisualLayers.RLeg,
        "LegRight" => PowerArmorVisualLayers.LLeg, 
        _ => PowerArmorVisualLayers.Chest,
    };
}