# Lambda
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleLambda
  name: Lambda Operative Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-nukie
    exclusiveAntag: true
    antagPrototype: Nukeops
  - type: NukeopsRole

- type: entity
  parent: MindRoleLambda
  id: MindRoleLambdaMedic
  name: Lambda Medic Role
  components:
  - type: MindRole
    antagPrototype: NukeopsMedic

- type: entity
  parent: MindRoleLambda
  id: MindRoleLambdaCommander
  name: Lambda Commander Role
  components:
  - type: MindRole
    antagPrototype: NukeopsCommander

- type: entity
  parent: MindRoleLambda
  id: MindRoleLambdaLoneops
  name: Lambda Loneops Operative Role
  components:
  - type: MindRole
    roleType: SoloAntagonist

# Traitors
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleTraitorNS
  name: Traitor Role
  components:
  - type: MindRole
    antagPrototype: Traitor
    exclusiveAntag: true
    subtype: role-subtype-traitor
  - type: TraitorRole

- type: entity
  parent: MindRoleTraitorNS
  id: MindRoleTraitorSleeperNS
  name: Sleeper Agent Role
  components:
  - type: MindRole
    antagPrototype: TraitorSleeper

- type: entity
  parent: MindRoleTraitorNS
  id: MindRoleTraitorReinforcementNS
  name: Syndicate Reinforcement Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-traitor-reinforcement
    antagPrototype: GenericTeamAntagonist