#region NT security vehicles

- type: entity
  id: CrateSecuritySecway
  parent: CrateSecgearNT
  name: Secway Crate
  description: A standard-issue secway for apprehending criminals, or a poor substitute for exercise. Probably both.
  components:
  - type: StorageFill
    contents:
      - id: VehicleSecwayFilled

- type: entity
  id: CrateSecuritySecwayTurbo
  parent: CrateSecgearNT
  name: Secway Turbo Crate
  description: A premium-grade secway for catching and shooting criminals at the same time.
  components:
  - type: StorageFill
    contents:
      - id: VehicleSecwayTurboFilled

- type: entity
  id: CrateSecuritySTV
  parent: CrateSecgearNT
  name: STV Crate
  description: A security-grade ATV for catching criminals and running over Tiders.
  components:
  - type: StorageFill
    contents:
      - id: VehicleATVNTSecFilled

#region NS security vehicles

- type: entity
  id: CrateSecuritySecwayNS
  parent: CrateSecgearNS
  name: Secway Crate
  description: A standard-issue secway for apprehending criminals, or a poor substitute for exercise. Probably both.
  components:
  - type: StorageFill
    contents:
      - id: VehicleSecwaySFilled

- type: entity
  id: CrateSecuritySecwayTurboNS
  parent: CrateSecgearNS
  name: Secway Turbo Crate
  description: A premium-grade secway for catching and shooting criminals at the same time.
  components:
  - type: StorageFill
    contents:
      - id: VehicleSecwayTurboFilled # Replace this with NS variant when it exists

- type: entity
  id: CrateSecuritySTVNS
  parent: CrateSecgearNS
  name: STV Crate
  description: A security-grade ATV for catching criminals and running over Tiders.
  components:
  - type: StorageFill
    contents:
      - id: VehicleATVNTSecFilled # Replace this with NS variant when it exists

#region implanters

- type: entity
  parent: CrateSecgearNS
  id: CrateSecurityTrackingMindshieldImplantsNS
  name: Implanter Crate
  description: Contains 4 NeoSol MindShield implants and 4 tracking implant. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: MindShieldImplanterNS
          amount: 4
        - id: TrackingImplanterNS
          amount: 4

- type: entity
  parent: CrateSecgearNT
  id: CrateSecurityTrackingMindshieldImplants
  name: Implanter Crate
  description: Contains 4 NanoTrasen MindShield implants and 4 tracking implant. Requires Security access to open. # FH
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: MindShieldImplanter
          amount: 4
        - id: TrackingImplanter
          amount: 4

#region NT armor
- type: entity
  parent: CrateSecgearNT
  id: CrateSecurityHelmet
  name: Helmet Crate
  description: Contains three standard-issue brain buckets. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: ClothingHeadHelmetBasic
          amount: 3

- type: entity
  parent: CrateSecgearNT
  id: CrateSecurityArmor
  name: Armor Crate
  description: Contains three bulletproof vests. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: ClothingOuterArmorBulletproof
          amount: 3
        - id: ClothingHeadHelmetBulletProof
          amount: 3

#region NS armor
- type: entity
  parent: CrateSecgearNS
  id: CrateSecurityHelmetNS
  name: Helmet Crate
  description: Contains three standard-issue brain buckets. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: ClothingHeadHelmetSecuritySyndi
          amount: 3

- type: entity
  parent: CrateSecgearNS
  id: CrateSecurityArmorNS
  name: Armor Crate
  description: Contains three bulletproof vests. Requires Security access to open.
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: ClothingOuterArmorBulletproofSyndi
          amount: 3
        - id: ClothingHeadHelmetBulletProofSyndi
          amount: 3