using Content.Client.UserInterface.Controls;
using Content.Shared._FarHorizons.Banking;
using Content.Shared._FarHorizons.Banking.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Banking.ATM;

[GenerateTypedNameReferences]
public sealed partial class CredstickATMWindow : FancyWindow
{
    public Action<int>? WithdrawRequest;

    private int? _cachedLimit;

    public CredstickATMWindow()
    {
        RobustXamlLoader.Load(this);

        Withdraw0.OnPressed += _ => RequestWithdrawal(0);
        Withdraw10.OnPressed += _ => RequestWithdrawal(10);
        Withdraw50.OnPressed += _ => RequestWithdrawal(50);
        Withdraw100.OnPressed += _ => RequestWithdrawal(100);
        Withdraw250.OnPressed += _ => RequestWithdrawal(250);
        Withdraw500.OnPressed += _ => RequestWithdrawal(500);
        Withdraw1000.OnPressed += _ => RequestWithdrawal(1000);
        WithdrawCustom.OnPressed += _ =>
        {
            WithdrawModalOverlay.Visible = true;
            WithdrawAmountInput.IsValid += v => int.TryParse(v, out var val) && val <= _cachedLimit;
        };

        WithdrawConfirmButton.OnPressed += _ => RequestWithdrawalCustom();
        WithdrawCancelButton.OnPressed += _ => CleanupPopup();
    }

    public void Populate(CredstickATMBuiState state)
    {
        _cachedLimit = state.Balance.Limit;

        BalanceAmountLabel.Text = Loc.GetString("frontier-bank-balance-text", ("balance", state.Balance.Balance));
        var limit = SharedBankingSystem.GetRemainingLimit(state.Balance);
        DailyLimitLabel.Text = Loc.GetString("frontier-bank-daily-limit-text", ("limit", limit));
    }

    private void RequestWithdrawalCustom()
    {
        if (!int.TryParse(WithdrawAmountInput.Text, out var val))
        {
            CleanupPopup();
            return;
        }

        RequestWithdrawal(val);
        CleanupPopup();
    }

    private void RequestWithdrawal(int amount) =>
        WithdrawRequest?.Invoke(amount);

    private void CleanupPopup()
    {
        WithdrawModalOverlay.Visible = false;
        WithdrawAmountInput.IsValid = null;
    }
}
