using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._FarHorizons.Banking.Credstick;

[GenerateTypedNameReferences]
public sealed partial class CredstickTransferDialogWindow : FancyWindow
{
    public Action<int>? TransferRequest;

    private int _maxAmount = 0;

    public CredstickTransferDialogWindow()
    {
        RobustXamlLoader.Load(this);

        TransferConfirmButton.OnPressed += _ => ConfirmTransfer();
        TransferCancelButton.OnPressed += _ => Close();
        TransferAmountSlider.OnValueChanged += OnSliderChanged;
    }

    public void SetLimit(int maxAmount) =>
        _maxAmount = maxAmount;
    
    private void OnSliderChanged(Robust.Client.UserInterface.Controls.Range val) =>
        TransferAmountInput.Text = ((int)(val.Value / 100f * _maxAmount)).ToString();

    private void ConfirmTransfer()
    {
        if (!int.TryParse(TransferAmountInput.Text, out var value))
            return;
        
        SendTransferRequest(value);
    }

    private void SendTransferRequest(int amount)
    {
        if (amount > 0)
            TransferRequest?.Invoke(amount);
        
        Close();
    }
}